[package]
name = "fictional_exporter"
version = "0.1.0"
authors = ["Santtu Pajukanta <santtu@pajukanta.fi>"]
edition = "2018"

[dependencies]
juniper = "^0.14.2"
juniper_warp = "^0.5.2"
itertools = "^0.9.0"
