[package]
name = "fictional_exporter"
version = "0.1.0"
authors = ["Santtu Pajukanta <santtu@pajukanta.fi>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
tokio = { version = "*", features = ["macros", "blocking", "rt-core"] }
warp = "0.1.8"
juniper = "*"
juniper_warp = "*"
env_logger = "*"